URI: http://localhost:5001
RessourceName: books
#Attributes must have a an id!
singleResourceName: book
attrbiutes:
  - id
  - title
  - abstract
  - author
  - length
  - rating

newEntity:
  id: null
  title: ''
  abstract: ''
  author: ''
  length: ''
  rating: ''