URI: http://localhost:5001
RessourceName: books
#Attributes must have a an id! - 'id' is directly used in many functions
singleResourceName: book
attrbiutes:
  - id: int
  - title: text
  - abstract: long
  - author: text
  - length: int
  - rating: float

#It need for the "ADD Object"
newEntity:
  id: null
  title: ''
  abstract: ''
  author: ''
  length: ''
  rating: ''
